version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cycle
      POSTGRES_PASSWORD: cycle
      POSTGRES_DB: cycle
    ports:
      - 6543:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data